import type { Metadata } from "next";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const zenKakuGothicNew = Zen_Kaku_Gothic_New({
	variable: "--font-zen-kaku-gothic-new",
	subsets: ["latin"],
	weight: ["300", "400", "500", "700", "900"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={zenKakuGothicNew.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
